FROM postgres:15.0-alpine
LABEL maintainer="jujin1324@daum.net"
LABEL dockerhub="https://hub.docker.com/_/postgres"

EXPOSE 5432

ENV POSTGRES_USER spring
ENV POSTGRES_PASSWORD security
ENV POSTGRES_DB spring_security
