server:
    port: 8999

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: spring
        password: security
        url: jdbc:mysql://localhost:3399/spring_security
    jpa:
        open-in-view: false
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
                jdbc:
                    time_zone: UTC
                    batch_size: 1000
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

decorator:
    datasource:
        p6spy:
            enable-logging: true

management:
    endpoints:
        web:
            exposure:
                include: health, info
    endpoint:
        health:
            show-details: never
    info:
        env:
            enabled: true

token:
    access:
        secretkey: AccessTokenSecretKey-local
