### CreatePhoneAuth
POST http://localhost:8999/authentication/phone
Content-Type: application/json

{
  "countryCode": "82",
  "phoneNo": "01012341234"
}

### VerifyPhoneAuth
POST http://localhost:8999/authentication/phone?verify=true
Content-Type: application/json

{
  "authId": "ad94bd2c-6731-40fd-96bb-1a2b6ca466ff",
  "verificationCode": "522510"
}

### GetAuthToken
GET http://localhost:8999/authentication/token
