### CreatePhoneAuth
POST http://localhost:8999/authentication/phone
Content-Type: application/json

{
  "countryCode": "82",
  "phoneNo": "01012341234"
}

### VerifyPhoneAuth
POST http://localhost:8999/authentication/phone?verify=true
Content-Type: application/json

{
  "authId": "17fb4762-4b4d-4caa-9335-9c92f79dfdf2",
  "verificationCode": "169560"
}

### GetAuthToken
GET http://localhost:8999/authentication/token
