### CreateUser
POST http://localhost:8999/users
Content-Type: application/json

{
  "nickname": "test nickname"
}

### GetSingleUser
GET http://localhost:8999/users/02473681-2b46-4fe1-ad17-7ca355ca88d2
